analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4875124152749777
  brandStrength: 1
  lightness: 0.1621506344527006
  brandColors:
    - '#FFFFFF'
    - '#6E6E6E'
    - '#000000'
    - '#FEBD00'
    - '#F38100'
  rhythmicContrast: 0.7246296706143767
typography_spectrum: 0.4587814
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3207885
favicon: null
name: Central Florida Trucking
